### ISSUE TITLE
Any plan to use the last version of tailwindcss? 

### ISSUE THREAD

**Issue by mustela** [Kamona-WD/kwd-dashboard#13]
Hey there! First of all! I love this theme! Great work! 

Second I tried to use the last version of tailwindcss, 2.216 and if you do that, the sidebar is gone, and I can't find the way to have it back, Im terrible with css sorry :/ 

Any clue? What's the magic behind the sidebar? How is it being shown/hidden? 

Thanks a lot!

**Comment by mustela** [comment]
You are right @Kamona-WD ! Sorry for the noice, I think it's another lib Im using in my project that was also updated.  Thanks for your quick response!

**Comment by Kamona-WD** [comment]
You are welcome
