### ISSUE TITLE
Keep Footer in bottom

### ISSUE THREAD

**Issue by hrace009** [Kamona-WD/kwd-dashboard#16]
Hello,
How i can keep this footer in bottom if have empty space?
![image](https://user-images.githubusercontent.com/7691118/153196266-a437c9b4-3306-471e-96a0-82be0f3b06ea.png)

Thanks

**Comment by Kamona-WD** [comment]
add `flex flex-col` classes to the div that contain `<header> & <main>  & <footer>`
add `flex-shrink-0` class to `<header>`
add `flex-1` class to `<main>`
add `flex-shrink-0` class to `<footer>`

![Screenshot from 2022-02-09 14-58-03](https://user-images.githubusercontent.com/57622665/153206635-46491100-c0c6-49bb-aed4-0491d309e969.png)
`

**Comment by hrace009** [comment]
nice, thank you
