### ISSUE TITLE
How to force only using dark theme?

### ISSUE THREAD

**Issue by hrace009** [Kamona-WD/kwd-dashboard#18]
Assalamualaikum,

How i can force only using dark theme?

Thanks

**Comment by Kamona-WD** [comment]
add `dark` class to `body` tag and remove dynamic `dark` class
```html
<body class="dark">
    <div x-data="setup()" x-init="$refs.loading.classList.add('hidden'); setColors(color);">
        <!--  -->
    </div>
</body>
```
and remove toggle button.
this is the quick way.

**Comment by hrace009** [comment]
> 

thanks, it work
